version: '3.4'

networks:
  NetExperienceNetwork:
services:
  net-experience:
    image: ${DOCKER_REGISTRY-}netexperience
    build:
      context: .
      dockerfile: src/Presentation/Api/Dockerfile
    networks:
      - NetExperienceNetwork
    depends_on:
      - mssql
  mssql:
    container_name: "sql"
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password@123
      - MSSQL_PID=Developer
    networks:
      - NetExperienceNetwork